environment:
  matrix:
    - PYTHON: "C:\\Python36-x64"

install:
  # We need wheel installed to build wheels
  - pip install .
  - pip install -r requirements_dev.txt

build: off

test_script:
  - pytest .

after_test:
  - codecov